"""
Attack evaluation suite for GHOST (Table III results).
Run compile.py first to train the HybridCNN and BaselineCNN models.

MIA evaluation protocol (Section IV-B):
  OOD  — non-members drawn from CIFAR-100 (distributional shift).
  SD   — non-members are held-out CIFAR-10 test samples (same distribution).
Both protocols use n_samples=5000 training members and n_test_samples=5000
test samples (5000 members + 5000 non-members = 10,000 total test samples,
consistent with "averaged over … 10,000 test samples" in Section IV).

Hardware: paper results on NVIDIA Tesla V100 (32 GB VRAM, CUDA 12.2).
"""
import os
import json
from typing import OrderedDict
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Subset
from PIL import Image
import csv
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, random_split
from torchvision import datasets, transforms
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Subset, TensorDataset
import torchvision
import torchvision.transforms as transforms
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import random
import torch
from torchsummary import summary
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Subset
import numpy as np
from sklearn.metrics import accuracy_score
import csv
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, random_split, Subset
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import os, csv
import torch
import torch.nn as nn
import time
import torch.optim as optim
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
torch.manual_seed(42)

#### SCROLL DOWN THIS IS STANDARD CODE FROM compile.py

device = "cuda" if torch.cuda.is_available() else "cpu"
# === CONFIGURATION ===
config = {
    "batch_size": 128,
    "shuffle_map_file": "shuffle_map.json",
    "key_file": "path_key.json",
    "num_epochs": 50,              # Section IV-A: 50 epochs for HybridCNN
    "learning_rate": 1e-3,
    "parallel_fake_layers": 4,     # N=4 encrypted decoy paths (Section IV-A)
    "device": "cuda" if torch.cuda.is_available() else "cpu",
    "test_image": "test.jpg",
    "model_file": "hybrid_cnn2.pth",
    "base_model_file": "baseline_cnn2.pth",
    "num_workers": 0,
}

# === PIXEL SHUFFLE HELPERS ===
def load_map(path):
    with open(path, 'r') as f:
        return json.load(f)

def shuffle_image(img, mapping):
    c, h, w = img.shape
    flat = img.view(c, -1)
    shuffled = flat[:, mapping]
    return shuffled.view(c, h, w)

# Prepare or load shuffle map
mapping = load_map(config['shuffle_map_file'])

# Load κ=128-bit token generated by train.py; generate a fresh one if train hasn't run yet
import hashlib as _hl_as, secrets as _sec_as
_TOKEN_FILE_AS = 'ghost_token.json'
if os.path.exists(_TOKEN_FILE_AS):
    with open(_TOKEN_FILE_AS) as _f: _td_as = json.load(_f)
    _token_hex = _td_as['token_hex']; _token_hash = _td_as['token_hash']
else:
    _tb_as = _sec_as.token_bytes(16)   # κ=128-bit
    _token_hex = _tb_as.hex(); _token_hash = _hl_as.sha256(_tb_as).hexdigest()
    with open(_TOKEN_FILE_AS, 'w') as _f:
        json.dump({'token_hex': _token_hex, 'token_hash': _token_hash}, _f)

# === TRANSFORMS ===
hybrid_transform = transforms.Compose([
    transforms.Resize((32, 32)), 
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop(32, padding=4),
    transforms.ToTensor(),
    transforms.Lambda(lambda x: shuffle_image(x, mapping)),
    transforms.Normalize((0.5,)*3, (0.5,)*3)
])

# Baseline model uses clean data + augmentation
baseline_transform = transforms.Compose([
    transforms.Resize((32,32)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop(32, padding=4),
    transforms.ToTensor(),
    transforms.Normalize((0.5,)*3, (0.5,)*3)
])

# === MODEL DEFINITION ===

# === UNSHUFFLE MODULE ===
class Unshuffle(nn.Module):
    """
    Inverts the pixel shuffle using the inverse mapping stored as a buffer.
    """
    def __init__(self, mapping):
        super().__init__()
        inv = torch.argsort(torch.tensor(mapping, dtype=torch.long))
        self.register_buffer('inv_map', inv)

    def forward(self, x):
        # x: [B, C, H, W]
        B,C,H,W = x.shape
        flat = x.view(B, C, -1)
        unshuffled = flat[:, :, self.inv_map]
        return unshuffled.view(B, C, H, W)
    
class _SpatialPerm(nn.Module):
    """Layer-wise spatial permutation π(l) — Section III-B."""
    def __init__(self, seed: int):
        super().__init__()
        self.seed = seed
        self.register_buffer('_p', None)
    def _build(self, n, device):
        g = torch.Generator(); g.manual_seed(self.seed)
        self._p = torch.randperm(n, generator=g).to(device)
    def forward(self, x):
        B, C, H, W = x.shape; n = H * W
        if self._p is None or self._p.numel() != n:
            self._build(n, x.device)
        return x.reshape(B, C, n)[:, :, self._p].reshape(B, C, H, W)

import hashlib as _hashlib
class _TokenGate(nn.Module):
    """SHA-256 hash verification gate — Section III-C."""
    def __init__(self, token_hash: str):
        super().__init__()
        self.token_hash = token_hash
    def forward(self, x, token: str = ''):
        try:
            computed = _hashlib.sha256(bytes.fromhex(token)).hexdigest()
        except Exception:
            computed = ''
        if computed != self.token_hash:
            return torch.zeros_like(x)
        return x

class HybridCNN(nn.Module):
    """HybridCNN: N=4 decoys, L=6 SpatialPerm, M=2 token gates (Section IV-A)."""
    NUM_PERMS = 6   # L=6

    def __init__(self, fake_layers, token_hash: str = ''):
        super().__init__()
        self.unshuffle = Unshuffle(mapping)

        # L=6 layer-wise spatial permutation modules (Section III-B)
        self.perms = nn.ModuleList([_SpatialPerm(1337 + l) for l in range(self.NUM_PERMS)])

        # M=2 token-gated access modules, κ=128-bit SHA-256 (Section III-C)
        self.gates = nn.ModuleList([_TokenGate(token_hash) for _ in range(2)])
        self._token_hash = token_hash

        self.conv1 = nn.Conv2d(3, 32, 3, padding=1)
        self.bn1   = nn.BatchNorm2d(32)
        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
        self.bn2   = nn.BatchNorm2d(64)
        self.pool  = nn.AvgPool2d(2, 2)   # Section IV-A: global average pooling
        self.fakes = nn.ModuleList([
            nn.Sequential(nn.Conv2d(64, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU())
            for _ in range(fake_layers)
        ])
        self.conv3   = nn.Conv2d(64, 128, 3, padding=1)
        self.bn3     = nn.BatchNorm2d(128)
        self.fc1     = nn.Linear(128 * 8 * 8, 256)
        self.dropout = nn.Dropout(0.5)
        self.fc2     = nn.Linear(256, 10)

    def forward(self, x, path_key=0, token=''):
        x = self.unshuffle(x)
        x = self.gates[0](x, token)          # gate 1: entry (Section III-C)

        # conv1 → perm at 32×32 → pool → 16×16  (Section F: (32²)! factor)
        x = F.relu(self.bn1(self.conv1(x)))   # 32×32
        x = self.perms[0](x)
        x = self.pool(x)                       # → 16×16

        # conv2 → perm at 16×16 → pool → 8×8  (Section F: (16²)! factor)
        x = F.relu(self.bn2(self.conv2(x)))   # 16×16
        x = self.perms[1](x)
        x = self.pool(x)                       # → 8×8

        # decoy routing + perm at 8×8  (first of four (8²)! factors)
        x = self.fakes[path_key % len(self.fakes)](x)
        x = self.perms[2](x)

        x = self.gates[1](x, token)           # gate 2: cloud boundary (Section III-C)

        # conv3 → three additional perms at 8×8  (Section F: three additional (8²)! factors)
        x = F.relu(self.bn3(self.conv3(x)))   # 8×8
        x = self.perms[3](x)
        x = self.perms[4](x)
        x = self.perms[5](x)

        x = x.view(x.size(0), -1)
        x = self.dropout(F.relu(self.fc1(x)))
        return self.fc2(x)

# === COMPARE TO ===
class BaselineCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 32, 3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        self.pool = nn.AvgPool2d(2, 2)   # Section IV-A: global average pooling
        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        self.fc1 = nn.Linear(64*8*8, 256)
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(256, 10)
    def forward(self, x):
        x = self.pool(F.relu(self.bn1(self.conv1(x))))
        x = self.pool(F.relu(self.bn2(self.conv2(x))))
        x = x.view(x.size(0), -1)
        x = self.dropout(F.relu(self.fc1(x)))
        return self.fc2(x)

# === KEY MANAGEMENT ===
def load_key(path):
    with open(path, 'r') as f:
        return json.load(f)["key"]

# === SPLIT RUN FUNCTIONS ===
def run_local(model, x, path_key=None):
    x = model.unshuffle(x)
    out = F.relu(model.bn1(model.conv1(x)))
    out = model.pool(F.relu(model.bn2(model.conv2(out))))
    if path_key is not None:
        idx = path_key % len(model.fakes)
        out = model.fakes[idx](out)
    return out

def run_cloud(model, out):
    # Simulate latency based on output size (number of elements)
    simulated_latency = out.numel() * 1e-8  # 10 nanoseconds per element (example)
    time.sleep(simulated_latency)

    out = F.relu(model.bn3(model.conv3(out)))   # conv3 stays at 8×8; no pool (Section F)
    out = out.view(out.size(0), -1)
    out = model.dropout(F.relu(model.fc1(out)))
    return out

def predict(model, x, token=''):
    key = torch.randint(0, len(model.fakes), (1,)).item()  # random per inference (Section IV-A)
    return model(x, path_key=key, token=token)



## =-========= ATTACKS START BELOW ===============


def substitute_model_attack(target_model, datapoints=5000, mtype=""):
    target_model.eval()
    target_model.to(device)

    # Use a standard transform
    transform = transforms.Compose([
        transforms.Resize((32,32)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomCrop(32, padding=4),
        transforms.ToTensor(),
        transforms.Normalize((0.5,)*3, (0.5,)*3)
    ])

    full_dataset = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
    test_dataset = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

    # Use a CIFAR10 subset to query the target model
    indices = np.random.choice(len(full_dataset), datapoints, replace=False)
    query_data = Subset(full_dataset, indices)
    query_loader = DataLoader(query_data, batch_size=64, shuffle=False)

    # Query the target model to get "soft labels"
    queried_images = []
    queried_labels = []

    with torch.no_grad():
        for inputs, _ in query_loader:
            inputs = inputs.to(device)
            if mtype == 'hybrid':
                outputs = predict(target_model, inputs, token=_token_hex)
            else:
                outputs = target_model(inputs)
            preds = outputs.argmax(dim=1).cpu()
            queried_images.append(inputs.cpu())
            queried_labels.append(preds)

    queried_images = torch.cat(queried_images)
    queried_labels = torch.cat(queried_labels)

    # Our simple substitute model
    class SimpleCNN(nn.Module):
        def __init__(self):
            super(SimpleCNN, self).__init__()
            self.conv1 = nn.Conv2d(3, 32, 3, padding=1)
            self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
            self.pool = nn.MaxPool2d(2, 2)
            self.fc1 = nn.Linear(64 * 8 * 8, 128)
            self.fc2 = nn.Linear(128, 10)

        def forward(self, x):
            x = self.pool(F.relu(self.conv1(x)))
            x = self.pool(F.relu(self.conv2(x)))
            x = x.view(-1, 64 * 8 * 8)
            x = F.relu(self.fc1(x))
            return self.fc2(x)

    substitute_model = SimpleCNN().to(device)

    # Training our substitute model our of the labels we got from the target model
    optimizer = optim.Adam(substitute_model.parameters(), lr=0.001)
    criterion = nn.CrossEntropyLoss()

    train_loader = DataLoader(
        list(zip(queried_images, queried_labels)),
        batch_size=64, shuffle=True
    )

    for epoch in range(10):
        substitute_model.train()
        total_loss = 0
        for x_batch, y_batch in train_loader:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)
            optimizer.zero_grad()
            outputs = substitute_model(x_batch)
            loss = criterion(outputs, y_batch)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        print(f"[Epoch {epoch+1}] Loss: {total_loss / len(train_loader):.4f}")

    # Evaluate substitute model on standard test set
    substitute_model.eval()
    test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

    all_preds = []
    all_labels = []

    with torch.no_grad():
        for x_batch, y_batch in test_loader:
            x_batch = x_batch.to(device)
            outputs = substitute_model(x_batch)
            preds = outputs.argmax(dim=1).cpu()
            all_preds.extend(preds.numpy())
            all_labels.extend(y_batch.numpy())

    acc = accuracy_score(all_labels, all_preds)
    print("\n=== Attack Summary ===")
    print(f"Substitute Model Accuracy on CIFAR-10 Test Set: {acc * 100:.2f}%")

    return acc * 100

def membership_inference_attack(target_model, mtype, n_samples=5000, n_test_samples=5000,
                                protocol='ood', csv_file="membership_attack_results.csv"):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    target_model.to(device)

    # Getting the probs from our target model
    def get_probs(model, mtype, loader):
        model.eval()
        model.to(device)
        outputs = []
        with torch.no_grad():
            for x, y in loader:
                x = x.to(device)
                if mtype == 'hybrid':
                    probs = F.softmax(predict(model, x, token=_token_hex), dim=1).cpu().numpy()
                else:
                    probs = F.softmax(model(x), dim=1).cpu().numpy()
                outputs.extend(probs)
        return outputs
    
    transform = transforms.Compose([
        transforms.Resize((32,32)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomCrop(32, padding=4),
        transforms.ToTensor(),
        transforms.Normalize((0.5,)*3, (0.5,)*3)
    ])

    # Members: CIFAR-10 train (seen during target-model training).
    # OOD non-members: pool of CIFAR-100 + SVHN + TinyImageNet + ImageNet-50k
    #   (4 distributional-shift sources, Section IV-B).
    # SD  non-members: CIFAR-10 test (same distribution, Table III SD column).
    #
    # TinyImageNet: download from http://cs231n.stanford.edu/tiny-imagenet-200.zip
    #   and unzip to ./data/tiny-imagenet-200/
    # ImageNet-50k: place a 50k-image subset (val split) at ./data/imagenet-50k/
    #   organised as ImageFolder (class_name/img.JPEG).
    cifar10_train  = torchvision.datasets.CIFAR10(root='./data',  train=True,  download=True, transform=transform)
    cifar10_test   = torchvision.datasets.CIFAR10(root='./data',  train=False, download=True, transform=transform)
    cifar100_train = torchvision.datasets.CIFAR100(root='./data', train=True,  download=True, transform=transform)
    cifar100_test  = torchvision.datasets.CIFAR100(root='./data', train=False, download=True, transform=transform)
    svhn_train     = torchvision.datasets.SVHN(root='./data',     split='train', download=True, transform=transform)
    svhn_test      = torchvision.datasets.SVHN(root='./data',     split='test',  download=True, transform=transform)

    # TinyImageNet (requires manual download; silently skipped if absent)
    _tinyimagenet_train = _tinyimagenet_val = None
    _tinyimagenet_path = os.path.join('./data', 'tiny-imagenet-200')
    if os.path.isdir(_tinyimagenet_path):
        _tinyimagenet_train = torchvision.datasets.ImageFolder(
            os.path.join(_tinyimagenet_path, 'train'), transform=transform)
        _val_dir = os.path.join(_tinyimagenet_path, 'val', 'images')
        if os.path.isdir(_val_dir):
            _tinyimagenet_val = torchvision.datasets.ImageFolder(_val_dir, transform=transform)
    else:
        print("[OOD] TinyImageNet not found at ./data/tiny-imagenet-200/ — skipping "
              "(download: http://cs231n.stanford.edu/tiny-imagenet-200.zip)")

    # ImageNet-50k (requires manual download; silently skipped if absent)
    _imagenet_train = _imagenet_val = None
    _imagenet_path  = os.path.join('./data', 'imagenet-50k')
    if os.path.isdir(_imagenet_path):
        _train_dir = os.path.join(_imagenet_path, 'train')
        _val_dir_in = os.path.join(_imagenet_path, 'val')
        if os.path.isdir(_train_dir):
            _imagenet_train = torchvision.datasets.ImageFolder(_train_dir, transform=transform)
        if os.path.isdir(_val_dir_in):
            _imagenet_val = torchvision.datasets.ImageFolder(_val_dir_in, transform=transform)
    else:
        print("[OOD] ImageNet-50k not found at ./data/imagenet-50k/ — skipping "
              "(requires manual download and ImageFolder organisation)")

    if protocol == 'sd':
        nonmember_train_ds = cifar10_test
        nonmember_test_ds  = cifar10_test
    else:
        # OOD: pool all 4 non-member sources (Section IV-B)
        from torch.utils.data import ConcatDataset
        ood_train_parts = [cifar100_train, svhn_train]
        ood_test_parts  = [cifar100_test,  svhn_test]
        if _tinyimagenet_train is not None:
            ood_train_parts.append(_tinyimagenet_train)
        if _tinyimagenet_val is not None:
            ood_test_parts.append(_tinyimagenet_val)
        if _imagenet_train is not None:
            ood_train_parts.append(_imagenet_train)
        if _imagenet_val is not None:
            ood_test_parts.append(_imagenet_val)
        nonmember_train_ds = ConcatDataset(ood_train_parts)
        nonmember_test_ds  = ConcatDataset(ood_test_parts)

    n_samples      = min(len(cifar10_train), len(nonmember_train_ds), n_samples)
    n_test_samples = min(len(cifar10_train), len(nonmember_test_ds),  n_test_samples)
    member_subset_train,    _ = random_split(cifar10_train,       [n_samples,      len(cifar10_train)       - n_samples],      generator=torch.Generator().manual_seed(42))
    nonmember_subset_train, _ = random_split(nonmember_train_ds,  [n_samples,      len(nonmember_train_ds)  - n_samples],      generator=torch.Generator().manual_seed(42))
    # Members for RF test must come from cifar10_train (seen during training); seed 43 ≠ 42 gives non-overlapping subset
    member_subset_test,     _ = random_split(cifar10_train,       [n_test_samples, len(cifar10_train)       - n_test_samples], generator=torch.Generator().manual_seed(43))
    nonmember_subset_test,  _ = random_split(nonmember_test_ds,   [n_test_samples, len(nonmember_test_ds)   - n_test_samples], generator=torch.Generator().manual_seed(42))

    member_loader_train = DataLoader(member_subset_train, batch_size=128)
    nonmember_loader_train = DataLoader(nonmember_subset_train, batch_size=128)
    member_loader_test = DataLoader(member_subset_test, batch_size=128)
    nonmember_loader_test = DataLoader(nonmember_subset_test, batch_size=128)

    # Get model output probabilities for train
    member_probs_train = get_probs(target_model, mtype, member_loader_train)
    nonmember_probs_train = get_probs(target_model, mtype, nonmember_loader_train)
    X_train = np.concatenate([member_probs_train, nonmember_probs_train])
    y_train = np.array([1]*len(member_probs_train) + [0]*len(nonmember_probs_train))

    # Train RandomForestClassifier as our attack model
    attack_model = RandomForestClassifier(n_estimators=100)
    attack_model.fit(X_train, y_train)

    # Get model output probabilities for test
    member_probs_test = get_probs(target_model, mtype, member_loader_test)
    nonmember_probs_test = get_probs(target_model, mtype, nonmember_loader_test)
    X_test = np.concatenate([member_probs_test, nonmember_probs_test])
    y_test = np.array([1]*len(member_probs_test) + [0]*len(nonmember_probs_test))

    # Predict and evaluate
    y_pred = attack_model.predict(X_test)
    y_score = attack_model.predict_proba(X_test)[:, 1]

    print("Membership Inference Attack Results (Test Data):")
    print(classification_report(y_test, y_pred, digits=4))
    print("AUC Score:", roc_auc_score(y_test, y_score))
    # Write results to CSV
    write_header = not os.path.exists(csv_file)
    with open(csv_file, "a", newline="") as f:
        writer = csv.writer(f)
        if write_header:
            writer.writerow(["model", "protocol", "n_samples", "n_test_samples", "accuracy", "precision", "recall", "f1", "auc"])
        accuracy  = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall    = recall_score(y_test, y_pred)
        f1        = f1_score(y_test, y_pred)
        auc_score = roc_auc_score(y_test, y_score)
        writer.writerow([mtype, protocol, n_samples, n_test_samples, accuracy, precision, recall, f1, auc_score])

def reverse_engineer(model_file, ref_model=None, input_shape=(3, 32, 32)):
    """Reconstruct architecture from state_dict and compute fidelity % (Section IV-D).

    Fidelity = fraction of reconstructed weight tensors whose shape exactly matches
    the reference model's state_dict (a proxy for structural reconstruction success).
    Baseline ~92.4%, GHOST ~14.6% (Section IV-D).
    """
    try:
        state_dict = torch.load(model_file, map_location='cpu')
    except Exception as e:
        print("Error loading .pth file:", e)
        return None, 0.0

    if isinstance(state_dict, dict) and 'state_dict' in state_dict:
        state_dict = state_dict['state_dict']

    print(f"\nKeys in state_dict: {list(state_dict.keys())[:6]} ...\n")

    layers = []
    layer_num = 0
    for key, weight in state_dict.items():
        if '.weight' not in key:
            continue
        if 'conv' in key:
            out_ch, in_ch, kH, kW = weight.shape
            layers.append((f'conv{layer_num}', nn.Conv2d(in_ch, out_ch, (kH, kW))))
        elif 'fc' in key or 'linear' in key:
            out_f, in_f = weight.shape
            layers.append((f'fc{layer_num}', nn.Linear(in_f, out_f)))
        layer_num += 1

    recon_model = nn.Sequential(OrderedDict(layers))
    print("Reconstructed Model Architecture:\n", recon_model)

    # Fidelity: shape-match fraction against reference (Section IV-D)
    fidelity = 0.0
    if ref_model is not None:
        ref_sd = ref_model.state_dict() if hasattr(ref_model, 'state_dict') else ref_model
        recon_sd = recon_model.state_dict()
        ref_shapes  = [tuple(v.shape) for v in ref_sd.values()]
        recon_shapes = [tuple(v.shape) for v in recon_sd.values()]
        matched = sum(rs == rr for rs, rr in zip(ref_shapes, recon_shapes))
        total   = max(len(ref_shapes), 1)
        fidelity = matched / total * 100
        print(f"Reconstruction fidelity: {fidelity:.1f}%  ({matched}/{total} layers matched)")
    else:
        print("Parameter shapes:")
        for k, v in state_dict.items():
            print(f"  {k:<40} {tuple(v.shape)}")

    return recon_model, fidelity

def model_prediction_stats(model, mtype, c=100):
    model.eval()
    with torch.no_grad():
        dummy_input = torch.randn(1, 3, 32, 32).to(next(model.parameters()).device)
        local_mem = 0
        cloud_mem = 0
        local_time = 0
        cloud_time = 0
        start_time = time.perf_counter()
        for _ in range(c):  # Warm-up
            if mtype == 'hybrid':
                torch.cuda.reset_peak_memory_stats()
                t0 = time.perf_counter()
                seg1 = run_local(model, dummy_input, load_key(config['key_file']))
                t1 = time.perf_counter()
                local_time += (t1 - t0)
                local_mem += torch.cuda.max_memory_allocated() if torch.cuda.is_available() else 0

                torch.cuda.reset_peak_memory_stats()
                t2 = time.perf_counter()
                seg2 = run_cloud(model, seg1)
                t3 = time.perf_counter()
                cloud_time += (t3 - t2)
                cloud_mem += torch.cuda.max_memory_allocated() if torch.cuda.is_available() else 0

                _ = model.fc2(seg2)
            else:
                torch.cuda.reset_peak_memory_stats()
                _ = model(dummy_input)
        end_time = time.perf_counter()
        avg_time = (end_time - start_time) / c
        print(f"Average inference time for {mtype} model: {avg_time:.6f} seconds")
        if mtype == 'hybrid':
            print(f"  Avg local time: {local_time / c:.6f} seconds")
            print(f"  Avg cloud time: {cloud_time / c:.6f} seconds")
            if torch.cuda.is_available():
                print(f"  Avg local memory usage: {local_mem / c / 1e6:.2f} MB")
                print(f"  Avg cloud memory usage: {cloud_mem / c / 1e6:.2f} MB")
        else:
            print(f"Peak memory usage for {mtype} model: {torch.cuda.max_memory_allocated() / 1e6:.2f} MB")
        torch.cuda.reset_peak_memory_stats()

if __name__ == '__main__':
    device = config['device']
    model = HybridCNN(config['parallel_fake_layers'], token_hash=_token_hash).to(device)
    base = BaselineCNN().to(device)
    model.load_state_dict(torch.load(config['model_file'], map_location=device))
    base.load_state_dict(torch.load(config['base_model_file'], map_location=device))
    print(f"Loaded model from {config['model_file']}")
    print(f"Loaded baseline model from {config['base_model_file']}")

    # Print model summaries
    model_prediction_stats(model, 'hybrid', 1000)
    model_prediction_stats(base, 'baseline', 1000)

    # Open-box reverse engineering fidelity (Section IV-D: baseline 92.4%, GHOST 14.6%)
    reverse_engineered_base,  fid_base  = reverse_engineer(config['base_model_file'], ref_model=base)
    reverse_engineered_model, fid_ghost = reverse_engineer(config['model_file'],      ref_model=model)
    print(f"Baseline fidelity: {fid_base:.1f}%  |  GHOST fidelity: {fid_ghost:.1f}%")

    # Membership Inference Attack Simulation
    # OOD protocol (Table III "MIA AUC OOD"): CIFAR-100 as non-members
    # SD  protocol (Table III "MIA AUC SD") : held-out CIFAR-10 test as non-members
    for model_obj, mtype in [(base, 'baseline'), (model, 'hybrid')]:
        model_obj.eval()
        for proto in ['ood', 'sd']:
            for ns in [1000, 2000, 5000, 10000]:
                membership_inference_attack(model_obj, mtype, n_samples=ns,
                                            n_test_samples=5000, protocol=proto)

    # Substitute Model Attack Simulation
    with open("substitute_attack_results.csv", "w", newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(["Model", "Datapoints", "Accuracy"])

        print("Hybrid model:")
        model.eval()
        # Table IV query budgets: 1k / 5k / 10k / 50k (Section IV-C)
        for dp in [1000, 5000, 10000, 50000]:
            acc = substitute_model_attack(model, dp, 'hybrid')
            writer.writerow(["hybrid", dp, acc])

        print("Baseline model:")
        base.eval()
        for dp in [1000, 5000, 10000, 50000]:
            acc = substitute_model_attack(base, dp, 'baseline')
            writer.writerow(["baseline", dp, acc])
